### ISSUE TITLE
Adjustments (maybe) needed for engine PR 3456

### ISSUE THREAD

**Issue by Cervator** [Terasology/GooeysQuests#31]
Merging MovingBlocks/Terasology#3456 makes starting GooeysQuests start the game with the following error - unsure exactly what assets/types cause the error, it repeats dozens upon dozens of times.

Sending this @eviltak's way as the author of the engine PR :-)

```
21:58:24.072 [main] WARN  o.t.p.s.ComponentSerializer - Cannot deserialize unknown field 'baseCooldownTime' onto 'engine:Item'
21:58:24.073 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab GooeysQuests:skeleton with inputs [/GooeysQuests/assets/prefabs/skeleton.prefab]
21:58:24.262 [main] ERROR o.t.m.s.WarnOnlyProviderFactory - Use of non-permitted class 'interface org.terasology.module.sandbox.API' detected by module 'Behaviors-0.2.0-SNAPSHOT': this should be fixed for production use
21:58:24.410 [main] WARN  o.t.p.s.ComponentSerializer - Cannot deserialize unknown field 'groundFriction' onto 'engine:CharacterMovement'
21:58:24.410 [main] WARN  o.t.p.s.ComponentSerializer - Cannot deserialize unknown field 'distanceBetweenSwimStrokes' onto 'engine:CharacterMovement'
21:58:25.488 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.StackOverflowError: null
	at org.terasology.reflection.TypeInfo.<init>(TypeInfo.java:68)
	at org.terasology.reflection.TypeInfo.of(TypeInfo.java:83)
	at org.terasology.persistence.typeHandling.mathTypes.factories.Rect2fTypeHandlerFactory.create(Rect2fTypeHandlerFactory.java:32)
	at org.terasology.persistence.typeHandling.TypeSerializationLibrary.getTypeHandler(TypeSerializationLibrary.java:230)
	at org.terasology.persistence.typeHandling.TypeSerializationLibrary.getTypeHandler(TypeSerializationLibrary.java:214)
	at org.terasology.persistence.typeHandling.coreTypes.factories.ArrayTypeHandlerFactory.create(ArrayTypeHandlerFactory.java:49)
	at org.terasology.persistence.typeHandling.TypeSerializationLibrary.getTypeHandler(TypeSerializationLibrary.java:230)
	at org.terasology.persistence.typeHandling.TypeSerializationLibrary.getTypeHandler(TypeSerializationLibrary.java:214)
	at org.terasology.persistence.typeHandling.coreTypes.factories.ObjectFieldMapTypeHandlerFactory.lambda$create$0(ObjectFieldMapTypeHandlerFactory.java:59)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.terasology.persistence.typeHandling.coreTypes.factories.ObjectFieldMapTypeHandlerFactory.create(ObjectFieldMapTypeHandlerFactory.java:54)
	at org.terasology.persistence.typeHandling.TypeSerializationLibrary.getTypeHandler(TypeSerializationLibrary.java:230)
	at org.terasology.persistence.typeHandling.TypeSerializationLibrary.getTypeHandler(TypeSerializationLibrary.java:214)
	at org.terasology.persistence.typeHandling.coreTypes.factories.ArrayTypeHandlerFactory.create(ArrayTypeHandlerFactory.java:49)
	at org.terasology.persistence.typeHandling.TypeSerializationLibrary.getTypeHandler(TypeSerializationLibrary.java:230)
	at org.terasology.persistence.typeHandling.TypeSerializationLibrary.getTypeHandler(TypeSerializationLibrary.java:214)
	at org.terasology.persistence.typeHandling.coreTypes.factories.ObjectFieldMapTypeHandlerFactory.lambda$create$0(ObjectFieldMapTypeHandlerFactory.java:59)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.terasology.persistence.typeHandling.coreTypes.factories.ObjectFieldMapTypeHandlerFactory.create(ObjectFieldMapTypeHandlerFactory.java:54)
	at org.terasology.persistence.typeHandling.TypeSerializationLibrary.getTypeHandler(TypeSerializationLibrary.java:230)
	at org.terasology.persistence.typeHandling.TypeSerializationLibrary.getTypeHandler(TypeSerializationLibrary.java:214)
	at org.terasology.persistence.typeHandling.coreTypes.factories.ArrayTypeHandlerFactory.create(ArrayTypeHandlerFactory.java:49)
	at org.terasology.persistence.typeHandling.TypeSerializationLibrary.getTypeHandler(TypeSerializationLibrary.java:230)
	at org.terasology.persistence.typeHandling.TypeSerializationLibrary.getTypeHandler(TypeSerializationLibrary.java:214)
	at org.terasology.persistence.typeHandling.coreTypes.factories.ObjectFieldMapTypeHandlerFactory.lambda$create$0(ObjectFieldMapTypeHandlerFactory.java:59)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
```

**Comment by Cervator** [comment]
Note: This is now tied to https://github.com/MovingBlocks/Terasology/issues/3490 instead - see it for details

**Comment by eviltak** [comment]
GooeysQuests seems to be working fine on the latest version of the `newSerialization` (MovingBlocks/Terasology#3535) engine branch. Can you confirm @Cervator?

**Comment by skaldarnar** [comment]
Same here:
- @Cervator did you got the chance to look at this? 
- @jdrueckert let's try this out =)

**Comment by jdrueckert** [comment]
@skaldarnar Don't recall: did we try this out? :thinking:
