### ISSUE TITLE
BlockRegion Precondition for Spawning Gooey

### ISSUE THREAD

**Issue by pollend** [Terasology/GooeysQuests#61]
```
14:21:59.229 [Thread-1] DEBUG c.j.d.entities.pipe.UnixPipe - Received packet: Pkt:FRAME{"evt":null,"data":{"assets":{"large_image":"515746954660151306"},"timestamps":{"start":1609453235000},"name":"Terasology","details":"Name: Player27452","state":"Solo | Game 40","type":0,"secrets":{},"application_id":"515274721080639504"},"cmd":"SET_ACTIVITY","nonce":"f61a32ae-eee3-4f88-a314-2cc6435b9858"}
14:22:02.494 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.IllegalArgumentException: null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:121)
	at org.terasology.world.block.BlockRegion.set(BlockRegion.java:179)
	at org.terasology.world.block.BlockRegion.<init>(BlockRegion.java:70)
	at org.terasology.math.JomlUtil.from(JomlUtil.java:198)
	at org.terasology.gooeysQuests.GooeySpawnSystem.isValidGooeySpawnPosition(GooeySpawnSystem.java:291)
	at org.terasology.gooeysQuests.GooeySpawnSystem.tryFindingGooeySpawnLocationInfrontOfCharacter(GooeySpawnSystem.java:226)
	at org.terasology.gooeysQuests.GooeySpawnSystem.tryToSpawnGooey(GooeySpawnSystem.java:165)
	at org.terasology.gooeysQuests.GooeySpawnSystem.update(GooeySpawnSystem.java:111)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:171)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:470)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:433)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:409)
	at org.terasology.engine.Terasology.main(Terasology.java:174)
14:22:02.495 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
14:22:02.496 [Chunk-Processing-Reactor] ERROR o.t.w.c.p.ChunkProcessingPipeline - Cannot run java.util.concurrent.ExecutorCompletionService$QueueingFuture@516ecbc2[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@44563dc2[Wrapped task = org.terasology.world.chunks.pipeline.PositionFuture@15480618]]  because queue is full
14:22:02.881 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
14:22:02.901 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
14:22:02.925 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: Player27452
14:22:02.928 [main] INFO  o.t.logic.console.ConsoleImpl - [NOTIFICATION] Player "Player27452" has left the game
14:22:02.930 [main] INFO  o.t.n.internal.NetworkSystemImpl - Network shutdown
14:22:02.964 [Thread-1] DEBUG c.j.d.entities.pipe.UnixPipe - Received packet: Pkt:FRAME{"evt":null,"data":{"assets":{"large_image":"515746954660151306"},"timestamps":{"start":1609453322000},"name":"Terasology","details":"Name: Player27452","state":"In Lobby","type":0,"secrets":{},"application_id":"515274721080639504"},"cmd":"SET_ACTIVITY","nonce":"1e5eba0b-2626-464f-b519-16ad11a3d5d1"}
14:22:03.219 [Engine-Task-Pool] INFO  o.t.rendering.opengl.ScreenGrabber - Screenshot saved to saves/Game 40/previews/1.jpg! 
14:22:04.056 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
14:22:04.059 [main] DEBUG c.j.d.entities.pipe.UnixPipe - Closing IPC pipe...
java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:121)
	at org.terasology.world.block.BlockRegion.set(BlockRegion.java:179)
	at org.terasology.world.block.BlockRegion.<init>(BlockRegion.java:70)
	at org.terasology.math.JomlUtil.from(JomlUtil.java:198)
	at org.terasology.gooeysQuests.GooeySpawnSystem.isValidGooeySpawnPosition(GooeySpawnSystem.java:291)
	at org.terasology.gooeysQuests.GooeySpawnSystem.tryFindingGooeySpawnLocationInfrontOfCharacter(GooeySpawnSystem.java:226)
	at org.terasology.gooeysQuests.GooeySpawnSystem.tryToSpawnGooey(GooeySpawnSystem.java:165)
	at org.terasology.gooeysQuests.GooeySpawnSystem.update(GooeySpawnSystem.java:111)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:171)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:470)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:433)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:409)
	at org.terasology.engine.Terasology.main(Terasology.java:174)
For more details, see the log files in /home/michaelpollind/drive/project/Terasology/logs/2020-12-31_14-19-56
Disconnected from the target VM, address: '127.0.0.1:58499', transport: 'socket'

Process finished with exit code 0

```

logs: https://gist.github.com/pollend/4dcf77b6a879a6751130e88cba79fb1f

**Comment by skaldarnar** [comment]
to be honest, it's pretty neat to find bugs like this now =) Should probably be simple enough to check for `null` at that location.
